# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pricing',
                'doc_host': 'https://Binjian.github.io',
                'git_url': 'https://github.com/Binjian/pricing',
                'lib_path': 'pricing'},
  'syms': {'pricing.core': {'pricing.core.foo': ('00.core.html#foo', 'pricing/core.py')}}}
